server:
  port: ${PORT:8081}

spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:hansol
    username: sa
    password: