server:
  port: 8080
---
spring:
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  application:
    name: client

sample:
  zipkin:
    enabled: true

